.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. CapStash_qt test_CapStash_qt
clean: FORCE
	$(MAKE) -C .. CapStash_qt_clean test_CapStash_qt_clean
check: FORCE
	$(MAKE) -C .. test_CapStash_qt_check
CapStash-qt CapStash-qt.exe: FORCE
	 $(MAKE) -C .. CapStash_qt
apk: FORCE
	$(MAKE) -C .. CapStash_qt_apk
